(define (sum-of-two-larger-squares x y z)
			(if (> x y)
				(if (> y z)
					(+ (* x x)(* y y))
				(+ (* x x)(* z z)))
				(if (> x z)
					(+ (* x x)(* y y))
				(+ (* y y)(* z z)))))
(sum-of-two-larger-squares 4 5 3)